create table if not exists public.myfans_permanent_candidate_exclusions (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('product', 'source')),
  entity_key text not null,
  product_id bigint references public.myfans_products(id) on delete set null,
  source_status_url text,
  quote_candidate_id bigint references public.myfans_quote_candidates(id) on delete set null,
  reason text not null check (reason in ('posted', 'user_skipped')),
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists myfans_permanent_candidate_exclusions_entity_idx
  on public.myfans_permanent_candidate_exclusions (entity_type, entity_key);

create index if not exists myfans_permanent_candidate_exclusions_product_idx
  on public.myfans_permanent_candidate_exclusions (product_id)
  where product_id is not null;

create index if not exists myfans_permanent_candidate_exclusions_source_idx
  on public.myfans_permanent_candidate_exclusions (source_status_url)
  where source_status_url is not null;

alter table public.myfans_permanent_candidate_exclusions enable row level security;
revoke all on table public.myfans_permanent_candidate_exclusions from anon, authenticated;
revoke all on sequence public.myfans_permanent_candidate_exclusions_id_seq from anon, authenticated;

-- Existing posted history is authoritative. Product rows are preferred; an
-- unlinked post is retained by its source URL without guessing a product.
insert into public.myfans_permanent_candidate_exclusions
  (entity_type, entity_key, product_id, source_status_url, reason, context, created_at)
select
  'product',
  'product:' || x.product_id::text,
  x.product_id,
  null,
  'posted',
  jsonb_build_object('backfilled_from', 'myfans_x_posts', 'post_id', x.id),
  coalesce(x.posted_at, x.created_at, now())
from public.myfans_x_posts x
where x.product_id is not null
  and (x.status = 'posted' or x.posted_at is not null or nullif(x.x_post_url, '') is not null)
on conflict (entity_type, entity_key) do nothing;

insert into public.myfans_permanent_candidate_exclusions
  (entity_type, entity_key, product_id, source_status_url, quote_candidate_id, reason, context, created_at)
select
  'source',
  'source:' || lower(trim(coalesce(nullif(x.quote_x_url, ''), nullif(x.source_x_url, '')))),
  null,
  coalesce(nullif(x.quote_x_url, ''), nullif(x.source_x_url, '')),
  null,
  'posted',
  jsonb_build_object('backfilled_from', 'myfans_x_posts', 'post_id', x.id),
  coalesce(x.posted_at, x.created_at, now())
from public.myfans_x_posts x
where x.product_id is null
  and nullif(trim(coalesce(nullif(x.quote_x_url, ''), nullif(x.source_x_url, ''))), '') is not null
  and (x.status = 'posted' or x.posted_at is not null or nullif(x.x_post_url, '') is not null)
on conflict (entity_type, entity_key) do nothing;
