import Link from "next/link";
import { getBijyoDashboard } from "@/lib/bijyoReservedAutoPost";
import { BijyoReservedActions } from "./BijyoReservedActions";
import { UpcomingBijyoReleases } from "./UpcomingBijyoReleases";

export const dynamic = "force-dynamic";

const SLOT_LABELS = ["1枠", "2枠", "3枠", "4枠"];
const STATUS_LABELS: Record<string, string> = { pending: "未投稿", posted: "投稿済み", manual_posted: "投稿済み（手動）", skipped: "スキップ", excluded: "対象外", trim_failed: "trimエラー" };

function dateLabel(value: string) { return new Date(value).toLocaleString("ja-JP", { timeZone: "Asia/Tokyo", month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }); }
function remaining(value: string) { return Math.max(0, Math.ceil((new Date(value).getTime() + 7 * 86_400_000 - Date.now()) / 86_400_000)); }
function previewUrl(jobId: number, workId: number) { return `/api/admin/bijyo-reserved/video?jobId=${jobId}&workId=${workId}&preview=1`; }
function previewSource(job: { id: number; work_id: number; trim_status: string; }, sampleMovieUrl: string) { return job.trim_status === "ready" ? previewUrl(job.id, job.work_id) : sampleMovieUrl; }

function JobCard({ job, index }: { job: Awaited<ReturnType<typeof getBijyoDashboard>>["todayJobs"][number]; index: number }) {
  const work = job.work;
  if (!work) return <div className="rounded-xl border border-rose-900 bg-rose-950/20 p-5">作品情報を取得できませんでした（work_id: {job.work_id}）。</div>;
  return <article className="rounded-xl border border-zinc-800 bg-zinc-950 p-5">
    <div className="flex flex-wrap items-center justify-between gap-2"><span className="rounded-full bg-violet-500/20 px-3 py-1 text-sm font-black text-violet-200">{SLOT_LABELS[index]}</span><span className="text-sm font-bold text-zinc-400">推奨 {new Date(job.scheduled_at).toLocaleTimeString("ja-JP", { timeZone: "Asia/Tokyo", hour: "2-digit", minute: "2-digit" })}</span><span className="text-sm font-black text-cyan-200">{STATUS_LABELS[job.status] ?? job.status}</span></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[220px_1fr]"><div><video controls preload="metadata" className="aspect-video w-full rounded-lg bg-black" src={previewSource(job, work.sample_movie_url)}><track kind="captions" /></video><p className="mt-2 text-xs text-zinc-500">{job.trim_status === "ready" ? "trim済みpreview" : "元動画preview（trim未生成）"}</p></div><div><Link href={`/works/${work.id}`} target="_blank" className="text-lg font-black text-cyan-300">{work.title}</Link><dl className="mt-3 grid grid-cols-2 gap-x-4 gap-y-2 text-xs text-zinc-400"><div><dt>work_id</dt><dd className="font-bold text-white">{work.id}</dd></div><div><dt>登録日</dt><dd className="font-bold text-white">{dateLabel(work.created_at)}</dd></div><div><dt>候補期限</dt><dd className="font-bold text-white">残り{remaining(work.created_at)}日</dd></div><div><dt>発売日</dt><dd className="font-bold text-white">{work.release_date}</dd></div><div><dt>自動trim開始</dt><dd className="font-bold text-white">{Number(job.trim_start_seconds).toFixed(1)}秒</dd></div><div><dt>trim準備</dt><dd className="font-bold text-white">{job.trim_status === "ready" ? "準備済み" : job.trim_status === "trim_failed" ? `失敗: ${job.trim_failure_reason ?? "理由不明"}` : "未生成（動画を開くで生成）"}</dd></div></dl><div className="mt-4 rounded-lg border border-zinc-800 bg-zinc-900 p-3"><p className="whitespace-pre-wrap text-sm font-bold">{job.main_text}</p><p className="mt-2 whitespace-pre-wrap text-xs text-violet-200">{job.reply_text}</p></div></div></div>
    <div className="mt-4"><BijyoReservedActions jobId={job.id} workId={work.id} mainText={job.main_text} replyText={job.reply_text} status={job.status} sampleMovieUrl={work.sample_movie_url} trimStartSeconds={job.trim_start_seconds} /></div>
  </article>;
}

function ManualJobCard({ job }: { job: Awaited<ReturnType<typeof getBijyoDashboard>>["jobs"][number] }) {
  const work = job.work;
  if (!work) return null;
  return <article className="rounded-xl border border-violet-800 bg-violet-950/10 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><span className="rounded-full bg-violet-500/20 px-3 py-1 text-sm font-black text-violet-200">手動追加</span><span className="text-sm font-black text-cyan-200">{STATUS_LABELS[job.status] ?? job.status}</span></div><div className="mt-4 grid gap-4 lg:grid-cols-[220px_1fr]"><div><video controls preload="metadata" className="aspect-video w-full rounded-lg bg-black" src={previewSource(job, work.sample_movie_url)}><track kind="captions" /></video><p className="mt-2 text-xs text-zinc-500">{job.trim_status === "ready" ? "trim済みpreview" : "元動画preview（trim未生成）"}</p></div><div><Link href={`/works/${work.id}`} target="_blank" className="text-lg font-black text-cyan-300">{work.title}</Link><p className="mt-2 text-xs text-zinc-500">work_id: {work.id} / trim: {Number(job.trim_start_seconds).toFixed(1)}秒 / {job.trim_status}</p><div className="mt-4 rounded-lg border border-zinc-800 bg-zinc-900 p-3"><p className="whitespace-pre-wrap text-sm font-bold">{job.main_text}</p><p className="mt-2 whitespace-pre-wrap text-xs text-violet-200">{job.reply_text}</p></div></div></div><div className="mt-4"><BijyoReservedActions jobId={job.id} workId={work.id} mainText={job.main_text} replyText={job.reply_text} status={job.status} sampleMovieUrl={work.sample_movie_url} trimStartSeconds={job.trim_start_seconds} /></div></article>;
}

export default async function BijyoReservedPage() {
  const dashboard = await getBijyoDashboard();
  return <main className="min-h-screen bg-zinc-950 p-6 text-white md:p-10"><div className="mx-auto max-w-7xl"><Link href="/admin" className="text-sm text-cyan-300">← ADMIN</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-[0.25em] text-violet-300">手動投稿司令塔</p><h1 className="mt-2 text-4xl font-black">@bijyo1010 予約作品 手動投稿</h1><p className="mt-2 text-zinc-400">毎日4件。動画・本文・自己リプを準備して、あなたがXへ手動投稿します。</p></div><div className="rounded-xl border border-cyan-700 bg-cyan-950/30 px-5 py-4"><p className="text-xs text-cyan-300">本日の進捗</p><p className="mt-1 text-3xl font-black">{dashboard.progress.posted}/{dashboard.progress.target}</p><p className="text-xs text-cyan-200">{dashboard.progress.shortage ? `候補不足 ${dashboard.progress.target - dashboard.progress.shortage}/4` : dashboard.progress.remaining ? `未投稿あと${dashboard.progress.remaining}件` : "完了"}</p></div></div>
    <nav aria-label="セクション内リンク" className="sticky top-2 z-10 mt-6 flex flex-wrap gap-2 rounded-xl border border-zinc-800 bg-zinc-950/95 p-2 text-sm shadow-lg shadow-black/20"><a href="#today" className="rounded-lg px-3 py-2 text-zinc-300 hover:bg-zinc-800 hover:text-white">今日の4件</a><a href="#manual" className="rounded-lg px-3 py-2 text-zinc-300 hover:bg-zinc-800 hover:text-white">手動追加</a><a href="#upcoming-releases" className="rounded-lg px-3 py-2 text-emerald-200 hover:bg-emerald-950/50">今後1週間</a><a href="#history" className="rounded-lg px-3 py-2 text-zinc-300 hover:bg-zinc-800 hover:text-white">履歴</a></nav>
    {dashboard.error && <p className="mt-6 rounded border border-rose-800 bg-rose-950/30 p-3 text-sm text-rose-200">データを取得できませんでした: {dashboard.error}</p>}
    <section id="today" className="mt-8 scroll-mt-20 rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">今日の4件</h2><p className="mt-1 text-sm text-zinc-400">09:00 / 13:00 / 18:00 / 22:00（日本時間）</p></div><span className="rounded-full border border-emerald-700 px-3 py-1 text-xs font-bold text-emerald-200">API自動投稿なし・手動運用</span></div><div className="mt-5 grid gap-5">{[0, 1, 2, 3].map((index) => { const job = dashboard.todayJobs.find((item) => item.slot_index === index); return job ? <JobCard key={job.id} job={job} index={index} /> : <div key={index} className="rounded-xl border border-dashed border-amber-800 bg-amber-950/10 p-6"><p className="font-black text-amber-200">{SLOT_LABELS[index]}：候補不足</p><p className="mt-2 text-sm text-zinc-400">過去7日以内の未投稿候補を確認しましたが、補充できる作品がありません。</p></div>; })}</div></section>
    <section id="manual" className="mt-8 scroll-mt-20 rounded-2xl border border-violet-800 bg-zinc-900 p-5"><h2 className="text-xl font-black">手動追加投稿</h2><p className="mt-1 text-sm text-zinc-400">選択済みの手動追加作品です。今日の4件にはカウントしません。</p><div className="mt-4 grid gap-5">{dashboard.jobs.filter((job) => job.kind === "manual" && ["pending", "trim_failed"].includes(job.status)).map((job) => <ManualJobCard key={job.id} job={job} />)}</div>{!dashboard.jobs.some((job) => job.kind === "manual" && ["pending", "trim_failed"].includes(job.status)) && <p className="rounded-lg border border-dashed border-violet-900 p-5 text-sm text-zinc-500">選択済みの手動追加作品はありません。</p>}<details className="mt-6 rounded-xl border border-zinc-800 bg-zinc-950"><summary className="cursor-pointer list-inside px-4 py-3 text-sm font-bold text-violet-200">追加候補を表示（{dashboard.candidates.length}件）</summary><div className="overflow-x-auto px-2 pb-2"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-xs text-zinc-500"><tr><th className="p-2">作品</th><th className="p-2">登録日</th><th className="p-2">候補期限</th><th className="p-2">発売日</th><th className="p-2">操作</th></tr></thead><tbody>{dashboard.candidates.map((work) => <tr key={work.id} className="border-t border-zinc-800"><td className="p-2"><Link href={`/works/${work.id}`} target="_blank" className="font-bold text-cyan-300">{work.title}</Link><p className="text-xs text-zinc-600">work_id: {work.id}</p></td><td className="p-2">{dateLabel(work.created_at)}</td><td className="p-2">残り{remaining(work.created_at)}日</td><td className="p-2">{work.release_date}</td><td className="p-2"><BijyoReservedActions workId={work.id} /></td></tr>)}</tbody></table>{!dashboard.candidates.length && <p className="p-6 text-sm text-zinc-500">現在、条件を満たす待機候補はありません。</p>}</div></details></section>
    <UpcomingBijyoReleases works={dashboard.recentReleased} />
    <section id="history" className="mt-8 scroll-mt-20 rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><h2 className="text-xl font-black">履歴</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-xs"><thead className="text-zinc-500"><tr><th className="p-2">日時</th><th className="p-2">区分</th><th className="p-2">slot</th><th className="p-2">work/title</th><th className="p-2">trim</th><th className="p-2">status</th><th className="p-2">理由</th><th className="p-2">本文 / 自己リプ</th></tr></thead><tbody>{dashboard.jobs.map((job) => <tr key={job.id} className="border-t border-zinc-800 align-top"><td className="p-2">{dateLabel(job.posted_at ?? job.scheduled_at)}</td><td className="p-2">{job.kind === "manual" ? "manual" : "daily 4"}</td><td className="p-2">{job.slot_index == null ? "追加" : `${job.slot_index + 1}枠`}</td><td className="p-2">{job.work_id}<br />{job.work?.title ?? "-"}</td><td className="p-2">{Number(job.trim_start_seconds).toFixed(1)}秒<br />{job.trim_status}</td><td className="p-2">{STATUS_LABELS[job.status] ?? job.status}</td><td className="p-2">{job.skip_reason ?? job.failure_reason ?? job.trim_failure_reason ?? "-"}</td><td className="whitespace-pre-wrap p-2">{job.main_text}<br /><span className="text-violet-200">{job.reply_text}</span></td></tr>)}</tbody></table>{!dashboard.jobs.length && <p className="p-6 text-sm text-zinc-500">履歴はまだありません。</p>}</div></section>
  </div></main>;
}
